SUBROUTINE ENSMEAN(EnMean,SVX,IDIMV,IDIMEn,Weights)

IMPLICIT NONE
      
INTEGER(KIND=4),INTENT(IN)  :: IDIMV
INTEGER(KIND=4),INTENT(IN)  :: IDIMEn
REAL(KIND=8),INTENT(INOUT)  :: EnMean
REAL(KIND=8),INTENT(IN)     :: SVX(IDIMV,IDIMEn)
REAL(KIND=8),INTENT(IN)     :: Weights(IDIMEn)
REAL(KIND=8)                :: EnMean1(IDIMV)

INTEGER(KIND=4)             :: I,J
INTEGER(KIND=4)             :: SUMM(IDIMV)

DO I = 1, IDIMV
   EnMean1(I) = SUM(SVX(I,:))/IDIMEn
   !EnMean1(I) = SUM(SVX(I,:)*Weights(:))
END DO
EnMean = SUM(EnMean1(:))/IDIMV

END SUBROUTINE ENSMEAN
