SUBROUTINE MODEL(XOUT,XIN,K,FORCE)

IMPLICIT NONE

REAL(KIND=8),INTENT(IN)     :: XIN, FORCE
INTEGER(KIND=4),INTENT(IN)  :: K
REAL(KIND=8),INTENT(INOUT)  :: XOUT

!XOUT = 0.5*XIN + 25*XIN/(1+XIN**2) + 8*COS(0.8*K) + FORCE
XOUT = XIN

END SUBROUTINE
