SUBROUTINE ENSMEAN(EnMean,SVX,IDIMV,IDIMEn)

IMPLICIT NONE
      
INTEGER(KIND=4),INTENT(IN)  :: IDIMV
INTEGER(KIND=4),INTENT(IN)  :: IDIMEn
REAL(KIND=8),INTENT(INOUT)  :: EnMean(IDIMV)
REAL(KIND=8),INTENT(IN)     :: SVX(IDIMV,IDIMEn)

INTEGER(KIND=4)             :: I,J
INTEGER(KIND=4)             :: SUMM(IDIMV)

DO I = 1, IDIMV
   EnMean(I) = SUM(SVX(I,:))/IDIMEn
END DO

END SUBROUTINE ENSMEAN
