PROGRAM PROGTEST
IMPLICIT NONE

INTEGER(KIND=4),PARAMETER   :: IDIMV = 6
INTEGER(KIND=4),ALLOCATABLE :: SEEDA(:)
REAL(KIND=8)                :: NDMean, NDVar
REAL(KIND=8),ALLOCATABLE    :: NDNumb(:)

ALLOCATE(SEEDA(IDIMV))
ALLOCATE(NDNumb(IDIMV))
SEEDA(:) = 10

NDMean     = 0
NDVar      = 0.16
NDNumb(:)  = 0.0

CALL NDGen(SEEDA, NDMean, NDVar, IDIMV, NDNumb)

PRINT*,NDNumb

END PROGRAM
