#!/bin/sh
# $Id: grib_configure_ifort12_linux 3741 2013-07-08 20:47:20Z frdo $
#
# GRIB shell script for a local configure for ROPP
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort12 / Linux
#
PREFIX=${1-$ROPP_ROOT/ifort12}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort12 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w" \
F77=ifort12  FFLAGS="-O2 -w" \
FC=ifort12  FCFLAGS="-O2 -w" \
              FLIBS="" LDFLAGS="" \
  ./configure --prefix=$PREFIX --disable-jpeg
