#!/bin/sh
# $Id: grib_configure_gfortran_cygwin 3741 2013-07-08 20:47:20Z frdo $
#
# GRIB shell script for a local configure for ROPP
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: gfortran / Cygwin
#
PREFIX=${1-$ROPP_ROOT/gfortran}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
gfortran --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w" \
F77=gfortran FFLAGS="-O2 -w" \
FC=gfortran FCFLAGS="-O2 -w" \
              FLIBS="" LDFLAGS="" \
  ./configure --prefix=$PREFIX --disable-jpeg
