#!/bin/sh
# $Id: grib_configure_ifort13_linux 3551 2013-02-25 09:51:28Z idculv $
#
# GRIB shell script for a local configure for ROPP
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort13 / Linux
#
PREFIX=${1-$ROPP_ROOT/ifort13}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort13 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w" \
F77=ifort13  FFLAGS="-O2 -w" \
FC=ifort13  FCFLAGS="-O2 -w" \
              FLIBS="" LDFLAGS="" \
  ./configure --prefix=$PREFIX --disable-jpeg
