#!/bin/sh
# $Id: grib_configure_ifort11_linux 3741 2013-07-08 20:47:20Z frdo $
#
# GRIB shell script for a local configure for ROPP
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort11 / Linux
#
PREFIX=${1-$ROPP_ROOT/ifort11}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort11 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w" \
F77=ifort11  FFLAGS="-O2 -w" \
FC=ifort11  FCFLAGS="-O2 -w" \
              FLIBS="" LDFLAGS="" \
  ./configure --prefix=$PREFIX --disable-jpeg
