#!/bin/sh
# $Id: grib_configure_nagfor_linux 3741 2013-07-08 20:47:20Z frdo $
#
# GRIB shell script for a local configure for ROPP
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: nagfor / Linux
#
PREFIX=${1-$ROPP_ROOT/nagfor}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
nagfor -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w" \
F77=nagfor   FFLAGS="-O2 -w" \
FC=nagfor   FCFLAGS="-O2 -w" \
              FLIBS="" LDFLAGS="" \
  ./configure --prefix=$PREFIX --disable-jpeg
