#!/bin/sh
# $Id: hdf5_configure_pgf95_linux 3007 2011-09-05 15:45:37Z frdo $
#
# hdf5 (v1.8.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf95 / Linux
#
PREFIX=${1-$ROPP_ROOT/pgf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf95 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w -I$PREFIX/include" \
FC=pgf95    FCFLAGS="-O2 -Mbackslash -I$PREFIX/include -I/opt/pgi/linux86/$ver/include" \
F77=pgf95    FFLAGS="-O2 -Mbackslash -I$PREFIX/include -I/opt/pgi/linux86/$ver/include" \
              FLIBS="" LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64 -L/opt/pgi/linux86/$ver/lib" \
  ./configure --prefix=$PREFIX   --enable-fortran \
              --disable-shared   --disable-cxx
