#!/bin/sh
# $Id: hdf5_configure_sunf95_linux 3007 2011-09-05 15:45:37Z frdo $
#
# hdf5 (v1.8.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: sunf95 / Linux
#
PREFIX=${1-$ROPP_ROOT/sunf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
sunf95 -V
echo
echo "C compiler:"
suncc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
# The following is needed so that configure can find where 
# libmtsk.so lives. This assumes suncc is directly in PATH and 
# is not found via a softlink. Modify 'sunroot' and/or 'sunlibs' 
# if this bit of code doesn't work for you.
sunpath=$(which suncc)
sunroot=${sunpath%/bin/suncc}
sunlibs=$sunroot/prod/lib/compilers/rtlibs/usr/lib/amd64
#
CXX="" \
CC=suncc    CFLAGS="-O -w -m64 -I$PREFIX/include" \
FC=sunf95  FCFLAGS="-O -w -m64 -I$PREFIX/include -moddir=./" \
             FLIBS="" LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64 -L$sunlibs" \
  ./configure --prefix=$PREFIX  --enable-fortran \
              --disable-shared  --disable-cxx
