#!/bin/sh
# $Id: hdf5_configure_gfortran_cygwin 3007 2011-09-05 15:45:37Z frdo $
#
# hdf5 (v1.8.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: gfortran / Cygwin
#
PREFIX=${1-$ROPP_ROOT/gfortran}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
gfortran --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w -I$PREFIX/include" \
FC=gfortran FCFLAGS="-O2 -w -I$PREFIX/include" \
F77=gfortran FFLAGS="-O2 -w -I$PREFIX/include" \
              FLIBS="" LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --prefix=$PREFIX   --enable-fortran \
              --disable-shared   --disable-cxx
