#!/bin/sh
# $Id: hdf5_configure_xlf95_aix 3007 2011-09-05 15:45:37Z frdo $
#
# hdf5 (v1.8.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: xlf95 / IBM AIX
#
PREFIX=${1-$ROPP_ROOT/xlf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
xlf95 -qversion
echo
echo "C compiler:"
xlc -qversion
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=xlc       CFLAGS="-O2 -w -q64 -I$PREFIX/include" \
F77=xlf      FFLAGS="-O2 -w -q64 -I$PREFIX/include" \
FC=xlf95    FCFLAGS="-O2 -w -q64 -qsuffix=f=f90 -I$PREFIX/include" \
            NMFLAGS="-X64" ARFLAGS="-X64 cru" \
              FLIBS="" LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --prefix=$PREFIX   --enable-fortran \
              --disable-shared   --disable-cxx
