#!/bin/sh
# $Id: netcdf_configure_ifort13_linux 3551 2013-02-25 09:51:28Z idculv $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort13 / Linux
#
PREFIX=${1-$ROPP_ROOT/ifort13}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort13 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo

CXX=gcc \
CC=gcc       CFLAGS="-O2 -w"      \
FC=ifort13  FCFLAGS="-O2 -w"      \
F77=ifort13  FFLAGS="-O2 -w"      \
              FLIBS="" LDFLAGS="" \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
