#!/bin/sh
# $Id: netcdf4_configure_ifort_linux 3738 2013-07-08 20:30:16Z frdo $
#
# netcdf-4 (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort / Linux
#
PREFIX=${1-$ROPP_ROOT/ifort}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w -I$PREFIX/include"                           \
FC=ifort    FCFLAGS="-O2 -w -cm -fp-port -vec-report0 -I$PREFIX/include" \
F77=ifort    FFLAGS="-O2 -w -cm -fp-port -vec-report0 -I$PREFIX/include" \
              FLIBS="" LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64"           \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-cxx                                \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
