#!/bin/sh
# $Id: netcdf4_configure_f95_sunos 3007 2011-09-05 15:45:37Z frdo $
#
# netcdf-4 (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: Sun f95 / SunOS
#
PREFIX=${1-$ROPP_ROOT/f95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
f95 -V
echo
echo "C compiler:"
cc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=cc        CFLAGS="-I$PREFIX/include"                          \
           CPPFLAGS="-DsunFortran"                               \
FC=f95      FCFLAGS="-fw -O -Am -M./ -Bstatic -I$PREFIX/include" \
F77=f95      FFLAGS="-fw -O -Am -M./ -Bstatic -I$PREFIX/include" \
              FLIBS="" LDFLAGS="-L$PREFIX/lib"             \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-cxx                                \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
