#!/bin/sh
# $Id: netcdf_configure_ifort_cygwin 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort / Cygwin
#
PREFIX=${1-$ROPP_ROOT/ifort}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort /logo
echo
echo "C compiler:"
cl /logo
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=cl        CFLAGS="-nologo -O2 -w -cm -Fo\$@" \
FC=ifort    FCFLAGS="-nologo -O2 -w -cm -Fo\$@" \
F77=ifort    FFLAGS="-nologo -O2 -w -cm -Fo\$@" \
              FLIBS="" LDFLAGS=""               \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
