#!/bin/sh
# $Id: netcdf4_configure_ifort_cygwin 3007 2011-09-05 15:45:37Z frdo $
#
# netcdf-4 (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort / Cygwin
#
PREFIX=${1-$ROPP_ROOT/ifort}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort /logo
echo
echo "C compiler:"
cl /logo
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=cl        CFLAGS="-nologo -O2 -w -cm -Fo\$@ -I$PREFIX/include" \
FC=ifort    FCFLAGS="-nologo -O2 -w -cm -Fo\$@ -I$PREFIX/include" \
F77=ifort    FFLAGS="-nologo -O2 -w -cm -Fo\$@ -I$PREFIX/include" \
              FLIBS="" LDFLAGS="-L$PREFIX/lib"                    \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-cxx                                \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
