#!/bin/sh
# $Id: netcdf_configure_f90_hp-ux 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: HP f90 / HP-UX
#
PREFIX=${1-$ROPP_ROOT/f90}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
/opt/fortran90/bin/f90 +version
echo
echo "C compiler:"
cc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=cc                      CFLAGS="-O2"           \
                         CPPFLAGS="-DhpuxFortran" \
FC=/opt/fortran90/bin/f90 FCFLAGS="-O2 -w"        \
F77=/opt/fortran90/bin/f90 FFLAGS="-O2 -w"        \
                            FLIBS="" LDFLAGS=""   \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
