#!/bin/sh
# $Id: netcdf_configure_xlf95_aix 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: xlf95 . IBM AIX
#
PREFIX=${1-$ROPP_ROOT/xlf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
xlf95 -qversion
echo
echo "C compiler:"
xlc -qversion
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=xlc       CFLAGS="-O2 -w -q64"                \
F77=xlf      FFLAGS="-O2 -w -q64"                \
FC=xlf95    FCFLAGS="-O2 -w -q64 -qsuffix=f=f90" \
            NMFLAGS="-X64" ARFLAGS="-X64 cru"    \
              FLIBS="" LDFLAGS=""                \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
