#!/bin/sh
# $Id: netcdf_configure_ifort9_linux 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: ifort9 / Linux
#
PREFIX=${1-$ROPP_ROOT/ifort9}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
ifort9 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX=gcc \
CC=gcc       CFLAGS="-O2 -w"                           \
FC=ifort9   FCFLAGS="-O2 -w -cm -fp-port -vec-report0" \
F77=ifort9   FFLAGS="-O2 -w -cm -fp-port -vec-report0" \
              FLIBS="" LDFLAGS=""                      \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
