#!/bin/sh
# $Id: netcdf_configure_nag_hp-ux 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: HP f95 / HP-UX
#
PREFIX=${1-$ROPP_ROOT/hpnag}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
f95 --version
echo
echo "C compiler:"
cc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=cc        CFLAGS="-O2 -w"                   \
           CPPFLAGS="-DNDEBUG -DNAGf90Fortran" \
FC=f95      FCFLAGS="-O2 -w -dusty -ieee=full" \
F77=f95      FFLAGS="-O2 -w -dusty -ieee=full" \
              FLIBS="" LDFLAGS=""              \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
