#!/bin/sh
# $Id: netcdf_configure_f95_sunos 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: Sun f95 / SunOS
#
PREFIX=${1-$ROPP_ROOT/f95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
f95 -V
echo
echo "C compiler:"
cc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=cc        CFLAGS=""                         \
           CPPFLAGS="-DsunFortran"             \
FC=f95      FCFLAGS="-fw -O -Am -M./ -Bstatic" \
F77=f95      FFLAGS="-fw -O -Am -M./ -Bstatic" \
              FLIBS="" LDFLAGS=""              \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
