#!/bin/sh
# $Id: netcdf_configure_g95_hp-ux 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x)  shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: g95 / HP-UX
#
PREFIX=${1-$ROPP_ROOT/g95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
g95 --version
echo
echo "C compiler:"
cc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w"       \
           CPPFLAGS="-Df2cFortran" \
FC=hpg95    FCFLAGS="-O2 -w"       \
F77=hpg95    FFLAGS="-O2 -w"       \
              FLIBS="" LDFLAGS=""  \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
