#!/bin/sh
# $Id: netcdf_configure_pgf6_linux 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf6 / Linux
#
PREFIX=${1-$ROPP_ROOT/pgf6}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf6 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w"      \
FC=pgf6     FCFLAGS="-O2 -w"      \
F77=pgf6     FFLAGS="-O2 -w"      \
              FLIBS="" LDFLAGS="" \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
