#!/bin/sh
# $Id: netcdf_configure_nagfor_linux 3739 2013-07-08 20:40:30Z frdo $
#
# netcdf (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: nagfor / Linux
#
PREFIX=${1-$ROPP_ROOT/nagfor}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
nagfor -V
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w"                   \
FC=nagfor   FCFLAGS="-O2 -w -dusty -ieee=full" \
F77=nagfor   FFLAGS="-O2 -w -dusty -ieee=full" \
              FLIBS="" LDFLAGS=""              \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-netcdf-4 --disable-cxx             \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
