#!/bin/sh
# $Id: netcdf4_configure_g95_cygwin 3215 2011-11-07 14:14:31Z frdo $
#
# netcdf-4 (v4.1.x)  shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: g95 / Cygwin
#
PREFIX=${1-$ROPP_ROOT/g95} 
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
g95 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=gcc       CFLAGS="-O2 -w -I$PREFIX/include" \
FC=g95      FCFLAGS="-O2 -w -I$PREFIX/include" \
F77=g95      FFLAGS="-O2 -w -I$PREFIX/include" \
              FLIBS="" LDFLAGS="-L$PREFIX/lib" \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-cxx                                \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran

