#!/bin/sh
# $Id: netcdf4_configure_efc_linux 3007 2011-09-05 15:45:37Z frdo $
#
# netcdf-4 (v4.1.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: efc / NEC TX
#
PREFIX=${1-$ROPP_ROOT/efc}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
efc -V
echo
echo "C compiler:"
ecc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CXX="" \
CC=ecc       CFLAGS="-O2 -w -cm -I$PREFIX/include"                  \
           CPPFLAGS="-DNAGf90Fortran"                               \
FC=efc      FCFLAGS="-O2 -w -cm -integer_size 64 -I$PREFIX/include" \
F77=efc      FFLAGS="-O2 -w -cm -integer_size 64 -I$PREFIX/include" \
              FLIBS="" F90LIBS="" LDFLAGS="-L$PREFIX/lib"  \
  ./configure --prefix=$PREFIX   --disable-option-checking \
              --disable-cxx                                \
              --disable-v2       --disable-dap             \
              --disable-shared   --disable-largefile       \
              --enable-separate-fortran
