#!/bin/sh
# $Id: ropp_configure_sgi_unix 3752 2013-07-09 18:55:03Z frdo $
#
# ROPP shell script for a configure.
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: SGI/MIPS f90 / IRIX-Unix
#
PREFIX=${1-$ROPP_ROOT/sgi}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
#fc#
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=cc \
F77=f90      FFLAGS="-O2 -w2 -I$PREFIX/include" \
FC=f90      FCFLAGS="-O2 -w2 -I$PREFIX/include" \
          AM_FFLAGS="" LDFLAGS="-L$PREFIX/lib"  \
  ./configure --prefix=$PREFIX

