#!/bin/sh
# $Id: ropp_configure_sunf95_sunos 3752 2013-07-09 18:55:03Z frdo $
#
# ROPP shell script for a local configure.
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: sunf95 / SunOS
#
PREFIX=${1-$ROPP_ROOT/sunf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
sunf95 -V
echo
echo "C compiler:"
suncc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=suncc \
F77=sunf95   FFLAGS="-O -ftrap=%none -I$PREFIX/include -moddir=./ -M$PREFIX/include -M../build" \
FC=sunf95   FCFLAGS="-O -ftrap=%none -I$PREFIX/include -moddir=./ -M$PREFIX/include -M../build" \
            LDFLAGS="-L$PREFIX/lib" \
  ./configure --prefix=$PREFIX
