#!/bin/sh
# $Id: ropp_configure_sunf95_linux 3769 2013-07-23 18:19:36Z frdo $
#
# ROPP shell script for a local configure.
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: sunf95 / Linux
#
PREFIX=${1-$ROPP_ROOT/sunf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
sunf95 -V
echo
echo "C compiler:"
suncc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=suncc \
FC=sunf95   FCFLAGS="-O -m64 -ftrap=%none -I$PREFIX/include -moddir=./ -M$PREFIX/include -M../build" \
            LDFLAGS="-L$PREFIX/lib -L$PREFIX/lib64" \
  ./configure --prefix=$PREFIX
