#!/bin/sh
# $Id: ropp_configure_xlf95_aix 3752 2013-07-09 18:55:03Z frdo $
#
# ROPP shell script for a local configure. 
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: xlf95 / IBM AIX
#
PREFIX=${1-$ROPP_ROOT/xlf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
xlf95 -qversion
echo
echo "C compiler:"
xlc -qversion
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=xlc \
F77=xlf      FFLAGS="-O2 -q64 -I$PREFIX/include" \
FC=xlf95    FCFLAGS="-O2 -q64 -I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib"\
  ./configure --prefix=$PREFIX --with-lowercase-modnames


