#!/bin/sh
# $Id: ropp_configure_pgf95_linux 3752 2013-07-09 18:55:03Z frdo $
#
# ROPP shell script for a local configure.
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf95 / Linux
#   
PREFIX=${1-$ROPP_ROOT/pgf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf95 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc \
F77=pgf95    FFLAGS="-O2 -Mbackslash -I$PREFIX/include" \
FC=pgf95    FCFLAGS="-O2 -Mbackslash -I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib   -L$PREFIX/lib64"   \
  ./configure --prefix=$PREFIX
