#!/bin/sh
# $Id: ropp_configure_nag_hp-ux 3752 2013-07-09 18:55:03Z frdo $
#
# ROPP shell script for a local configure.
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: NAG f95 / HP-UX
#
PREFIX=${1-$ROPP_ROOT/nag}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
f95 --version
echo
echo "C compiler:"
cc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc \
F77=f95      FFLAGS="-O2 -dusty -I$PREFIX/include" \
FC=f95      FCFLAGS="-O2 -dusty -I$PREFIX/include" \
            LDFLAGS="-L$PREFIX/lib" \
  ./configure --prefix=$PREFIX
