#!/bin/sh
# $Id: zlib_configure_sunf95_linux 3007 2011-09-05 15:45:37Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: sunf95 / Linux
#
PREFIX=${1-$ROPP_ROOT/sunf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
sunf95 -V
echo
echo "C compiler:"
suncc -V
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=suncc     CFLAGS="-O -w -m64" \
  ./configure --static --prefix=$PREFIX
