#!/bin/sh
# $Id: zlib_configure_xlf95_aix 3007 2011-09-05 15:45:37Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: xlf95 / IBM AIX
#
PREFIX=${1-$ROPP_ROOT/xlf95}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
xlf95 -qversion
echo
echo "C compiler:"
xlc -qversion
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=xlc       CFLAGS="-O2 -w -q64" \
            NMFLAGS="-X64" ARFLAGS="-X64 cru" \
  ./configure --static --prefix=$PREFIX
