#!/bin/sh
# $Id: zlib_configure_pgf10_linux 3007 2011-09-05 15:45:37Z frdo $
#
# zlib (v1.2.x) shell script for a local configure
# USERS SHOULD MODIFY THIS SCRIPT AS REQUIRED FOR LOCAL INSTALL
#
# Compiler: pgf10 / Linux
#
PREFIX=${1-$ROPP_ROOT/pgf10}
echo
echo "Platform:"
uname -a
echo
echo "Fortran compiler:"
pgf10 --version
echo
echo "C compiler:"
gcc --version
echo
echo "Installation target:"
echo "$PREFIX"
echo
#
CC=gcc       CFLAGS="-O2 -w" \
  ./configure --static --prefix=$PREFIX
