! $Id: ropp_io_write.f90 3551 2013-02-25 09:51:28Z idculv $

!****s* Writing/ropp_io_write *
!
! NAME
!    ropp_io_write - Write an ROPP data file.
!
! SYNOPSIS
!    call ropp_io_write(data [, file=...] [, path=...], [,output_precision=...],
!                            [, append=...] [, rec=...] [, ranchk=...]
!                            [, ierr=...])
!
! DESCRIPTION
!    This subroutine writes RO event data to a specified file. The file
!    written conforms to the ROPP v1.1 data format and is netCDF based.
!
! INPUTS
!    data  dtyp   one of the output data types defined in ropp_io_types:
!                    ROprof
!                    <TBD>
!    file    chr    name of output file (optional; default is autogenerated)
!    path    chr    name of path for output directory (optional; default is PWD)
!    output_precision   'che float' or 'double' (optional; default is float)

!    multi   log    multiple-profile flag (optional). Valid values are:
!                    - .T. create single file with multiple profiles
!                    - .F. create different files for multiple profiles
!    append  log    file append flag (optional). Valid values are:
!                    - .T. append to existing file
!                    - .F. start a new file (overwrite any existing file) (default)
!    rec     int    specific record to write for multifiles (optional)
!                   (default: next record in sequence)
!    ranchk  log    range check flag (optional) Valid values are:
!                    - .T. to perform a range check prior to output (default) or
!                    - .F. to skip range checking
!                   This flag should not normally be used or if present, be
!                   set to default .T.. It is intended for use only when
!                   deliberately invalid data is explicitly required to
!                   survive into the output netCDF file, such as when
!                   generating invalid data for testing of downstream Q/C.
!
! OUTPUT
!    ierr  int    exit I/O code;
!                    -  0 = ok
!                    - -1 = unexpected EOF
!                    - I/O error (system dependent or as obtained from netCDF)
!
! NOTES
!    If file is not given, a file name will be autogenerated based on the
!    content of the of the data structure (using the occ_id element of the
!    data structure).
!
!    If ierr is not given, the routine will abort in case of an error.
!
! SEE ALSO
!    ropp_io
!    ropp_io_types
!    ropp_io_read
!    ropp_io_occid
!
! CALLS
!    ropp_io_write_ncdf
!
! AUTHOR
!   Met Office, Exeter, UK.
!   Any comments on this software should be given via the ROM SAF
!   Helpdesk at http://www.romsaf.org
!
! COPYRIGHT
!   (c) EUMETSAT. All rights reserved.
!   For further details please refer to the file COPYRIGHT
!   which you should have received as part of this distribution.
!
!****

!-------------------------------------------------------------------------------
! 1. Writing a single profile of ROprof data (netCDF)
!-------------------------------------------------------------------------------

SUBROUTINE ropp_io_write_rodatass(ROdata, file, path, output_precision, &
                                          append, rec, ranchk, ierr)

! 1.1 Declarations
! ----------------

  USE ropp_utils
  USE ncdf
  USE ropp_io,       not_this => ropp_io_write_rodatass
  USE ropp_io_types, ONLY: ROprof, &
                           ropp_io_ncopensep

  IMPLICIT NONE

  TYPE(ROprof),       INTENT(inout) :: ROdata
  CHARACTER(len = *), OPTIONAL      :: file
  CHARACTER(len = *), OPTIONAL      :: path
  CHARACTER(len = *), OPTIONAL      :: output_precision
  LOGICAL,            OPTIONAL      :: append
  LOGICAL,            OPTIONAL      :: ranchk
  INTEGER,            OPTIONAL      :: rec
  INTEGER,            OPTIONAL      :: ierr

  LOGICAL                           :: iappend
  LOGICAL                           :: iranchk
  LOGICAL                           :: exist
  INTEGER                           :: irec

  CHARACTER(len = 1024)             :: filename
  CHARACTER(len =  256)             :: filebase
  CHARACTER(len =    6)             :: filetype
  CHARACTER(len =    6)             :: fileext
  CHARACTER(len =  256)             :: routine

! 1.2 Error handling
! ------------------

  IF (PRESENT(ierr)) THEN
     ierr = 0
  ELSE
     CALL message_get_routine(routine)
     CALL message_set_routine('ropp_io_write')
  ENDIF

! 1.3 Default arguments
! ---------------------

  IF (PRESENT(append)) THEN
     iappend = append
  ELSE
     iappend = .FALSE.
  ENDIF

  IF (PRESENT(rec)) THEN
     irec = rec
  ELSE
     irec = -1
  ENDIF

  IF (PRESENT(ranchk)) THEN
    iranchk = ranchk
  ELSE
    iranchk = .TRUE.
  ENDIF

! 1.4 File type
! -------------

  filetype = 'netcdf'
  fileext  = '.nc'

! 1.4 Range check Q/C
! --------------------------------------------------

  IF ( iranchk ) CALL ropp_io_rangecheck(ROdata)

! 1.5 Provide output file name (if not already present)
! ------------------------------------------------------------------------

  filebase = TRIM(ROdata%occ_id)
  CALL To_Lower(filebase)
  IF (iappend) THEN
     IF (PRESENT(file)) THEN
        IF (file == " ") THEN
           CALL message(msg_fatal, &
                "File name must not be empty for appending profiles.")
        ELSE
           filename = TRIM(file)
        ENDIF
     ELSE
        CALL message(msg_fatal, &
             "File name required for appending profiles.")
     ENDIF
  ELSE
     IF (PRESENT(file)) THEN
        IF (file == " ") THEN
           filename = TRIM(filebase) // TRIM(fileext)
        ELSE
           filename = TRIM(file)
        ENDIF
     ELSE
        filename = TRIM(filebase) // TRIM(fileext)
     ENDIF
  ENDIF

! 1.6 Prepend filename with path (if present)
! -------------------------------------------

  IF (PRESENT(path)) THEN
     filename = TRIM(path) // TRIM(filename)
  ENDIF

! 1.7 Write netCDF data file
! --------------------------

  IF (.NOT. ropp_io_ncopensep) THEN
     INQUIRE(file = filename, exist = exist)
     IF (exist .AND. iappend) THEN
        CALL ncdf_open(filename, append = .TRUE.)
     ELSE
        CALL ncdf_create(filename)
        IF (PRESENT(output_precision)) THEN
           CALL ropp_io_write_ncdf_def(ROdata, output_precision)
        ELSE
           CALL ropp_io_write_ncdf_def(ROdata)
        ENDIF
     ENDIF
  ENDIF

  IF (irec <= 0) THEN
     irec = ncdf_getnrec() + 1
  ENDIF
  CALL ropp_io_write_ncdf_put(ROdata, rec = irec)

  IF (.NOT. ropp_io_ncopensep) THEN
     CALL ncdf_close()
  ENDIF

! 1.8 Clean up
! ------------

  IF (.NOT. PRESENT(ierr)) THEN
     CALL message_set_routine(routine)
  ENDIF

END SUBROUTINE ropp_io_write_rodatass


!-------------------------------------------------------------------------------
! 2. Write multiple profiles of ROprof data
!-------------------------------------------------------------------------------

SUBROUTINE ropp_io_write_rodatamm(ROdata, filelst, path, output_precision, &
                                          multi, append, rec, ranchk, ierr)

! 2.1 Declarations
! ----------------

  USE ropp_utils
  USE ncdf
  USE ropp_io,       not_this => ropp_io_write_rodatamm
  USE ropp_io_types, ONLY: ROprof, &
                           ropp_io_ncopensep

  IMPLICIT NONE

  TYPE(ROprof), DIMENSION(:),       INTENT(inout) :: ROdata
  CHARACTER(len = *), DIMENSION(:), OPTIONAL      :: filelst
  CHARACTER(len = *),               OPTIONAL      :: path
  CHARACTER(len = *),               OPTIONAL      :: output_precision
  LOGICAL,                          OPTIONAL      :: multi
  LOGICAL,                          OPTIONAL      :: append
  LOGICAL,                          OPTIONAL      :: ranchk
  INTEGER,                          OPTIONAL      :: rec
  INTEGER,                          OPTIONAL      :: ierr

  LOGICAL                                         :: imulti
  LOGICAL                                         :: iappend
  LOGICAL                                         :: iranchk
  LOGICAL                                         :: exist
  INTEGER                                         :: i, irec
  INTEGER                                         :: nfiles

  CHARACTER(len = 1024), DIMENSION(SIZE(ROdata))  :: filename
  CHARACTER(len =  256)                           :: filebase
  CHARACTER(len =    6)                           :: filetype
  CHARACTER(len =    6)                           :: fileext
  CHARACTER(len =  256)                           :: routine

! 2.2 Error handling
! ------------------

  IF (PRESENT(ierr)) THEN
     ierr = 0
  ELSE
     CALL message_get_routine(routine)
     CALL message_set_routine('ropp_io_write')
  ENDIF

! 2.3 Check arguments
! -------------------

  IF (SIZE(filelst) /= SIZE(ROdata)) THEN
     CALL message(msg_fatal, &
          "Number of profiles and number of filenames must be identical.")
  ENDIF

! 2.4 Default arguments
! ---------------------

  IF (PRESENT(append)) THEN   ! Append to an already existing file?
     iappend = append
  ELSE
     iappend = .FALSE.
  ENDIF

  IF (PRESENT(multi)) THEN    ! Create a multi-profile data file
     imulti = multi
  ELSE
     imulti = .FALSE.
  ENDIF

  IF (PRESENT(rec)) THEN
     irec = rec
  ELSE
     irec = -1
  ENDIF

  IF (PRESENT(ranchk)) THEN
    iranchk = ranchk
  ELSE
    iranchk = .TRUE.
  ENDIF

! 2.5 File type
! -------------

  filetype = 'netcdf'
  fileext  = '.nc'

! 2.6 Range check Q/C and provide file name(s) for output
! --------------------------------------------------------

  nfiles = SIZE(ROdata)
  IF(imulti) nfiles=1

  DO i = 1, nfiles

     IF ( iranchk ) CALL ropp_io_rangecheck(ROdata(i))

     filebase = TRIM(ROdata(i)%occ_id)
     CALL To_Lower(filebase)

     IF(iappend)THEN
        IF(PRESENT(filelst))THEN
           IF(filelst(i) == "")THEN
               CALL message(msg_fatal, &
                    "File names must not be empty for appending profiles.")
            ELSE
               filename(i) = TRIM(filelst(i))
            ENDIF
         ELSE
            CALL message(msg_fatal, &
             "File name required for appending profiles.")
         ENDIF
     ELSE
        IF(PRESENT(filelst))THEN
           IF (filelst(i) == " ") THEN
              filename(i) = TRIM(filebase) // TRIM(fileext)
           ELSE
              filename(i) = filelst(i)
           ENDIF
        ELSE
           filename(i) = TRIM(filebase) // TRIM(fileext)
        ENDIF
     ENDIF

! 2.7 Prepend filenames with path (if present)
! --------------------------------------------

     IF (PRESENT(path)) THEN
        filename(i) = TRIM(path) // TRIM(filename(i))
     ENDIF

  ENDDO

! 2.8 Write multi-profile data file
! ---------------------------------

  IF (imulti) THEN

     IF (.NOT. ropp_io_ncopensep) THEN
        INQUIRE(file = filename(1), exist = exist)
        IF (exist .AND. iappend) THEN
           CALL ncdf_open(filename(1), append = .TRUE.)
        ELSE
           CALL ncdf_create(filename(1))
           IF (PRESENT(output_precision)) THEN
              CALL ropp_io_write_ncdf_def(ROdata(1), output_precision)
           ELSE
              CALL ropp_io_write_ncdf_def(ROdata(1))
           ENDIF
        ENDIF
     ENDIF

     IF (irec <= 0) THEN
        irec = ncdf_getnrec() + 1
     ENDIF

     DO i = 1, SIZE(ROdata)
        CALL ropp_io_write_ncdf_put(ROdata(i), rec = (irec + i - 1))
     ENDDO

     IF (.NOT. ropp_io_ncopensep) THEN
        CALL ncdf_close()
     ENDIF

! 2.9 Several single-profile data files
! -------------------------------------

  ELSE

     DO i = 1, SIZE(ROdata)

        IF (.NOT. ropp_io_ncopensep) THEN
           INQUIRE(file = filename(i), exist = exist)
           IF (exist .AND. iappend) THEN
              CALL ncdf_open(filename(i), append = .TRUE.)
           ELSE
              CALL ncdf_create(filename(i))
              IF (PRESENT(output_precision)) THEN
                 CALL ropp_io_write_ncdf_def(ROdata(i),output_precision)
              ELSE
                 CALL ropp_io_write_ncdf_def(ROdata(i))
              ENDIF
           ENDIF
        ENDIF

        IF (irec <= 0) THEN
           irec = ncdf_getnrec() + 1
        ENDIF
        CALL ropp_io_write_ncdf_put(ROdata(i), rec = irec)

        IF (.NOT. ropp_io_ncopensep) THEN
           CALL ncdf_close()
        ENDIF

     ENDDO

  ENDIF

! 2.10 Clean up
! ------------

  IF (.NOT. PRESENT(ierr)) THEN
     CALL message_set_routine(routine)
  ENDIF

END SUBROUTINE ropp_io_write_rodatamm

!-------------------------------------------------------------------------------
! 3. Writing a single profile of ROprof data (netCDF) - 2D DATA
!-------------------------------------------------------------------------------

SUBROUTINE ropp_io_write_rodata2d(ROdata, file, path, output_precision, &
                                          append, rec, ranchk, ierr)

! 3.1 Declarations
! ----------------

  USE ropp_utils
  USE ncdf
  USE ropp_io,       not_this => ropp_io_write_rodata2d
  USE ropp_io_types, ONLY: ROprof2d, &
                           ropp_io_ncopensep

  IMPLICIT NONE

  TYPE(ROprof2d),     INTENT(inout) :: ROdata
  CHARACTER(len = *), OPTIONAL      :: file
  CHARACTER(len = *), OPTIONAL      :: path
  CHARACTER(len = *), OPTIONAL      :: output_precision
  LOGICAL,            OPTIONAL      :: append
  LOGICAL,            OPTIONAL      :: ranchk
  INTEGER,            OPTIONAL      :: rec
  INTEGER,            OPTIONAL      :: ierr

  LOGICAL                           :: iappend
  LOGICAL                           :: iranchk
  LOGICAL                           :: exist
  INTEGER                           :: irec

  CHARACTER(len = 1024)             :: filename
  CHARACTER(len =  256)             :: filebase
  CHARACTER(len =    6)             :: filetype
  CHARACTER(len =    6)             :: fileext
  CHARACTER(len =  256)             :: routine

! 3.2 Error handling
! ------------------

  IF (PRESENT(ierr)) THEN
     ierr = 0
  ELSE
     CALL message_get_routine(routine)
     CALL message_set_routine('ropp_io_write')
  ENDIF

! 3.3 Default arguments
! ---------------------

  IF (PRESENT(append)) THEN
     iappend = append
  ELSE
     iappend = .FALSE.
  ENDIF

  IF (PRESENT(rec)) THEN
     irec = rec
  ELSE
     irec = -1
  ENDIF

  IF (PRESENT(ranchk)) THEN
    iranchk = ranchk
  ELSE
    iranchk = .TRUE.
  ENDIF

! 3.4 File type
! -------------

  filetype = 'netcdf'
  fileext  = '.nc'

! 3.5 Range check Q/C - currently only 1d
! --------------------------------------------------

!!  if ( iranchk ) call ropp_io_rangecheck(ROdata)

! 3.6 Provide output file name (if not already present)
! ------------------------------------------------------------------------

  filebase = TRIM(ROdata%occ_id)
  CALL To_Lower(filebase)

  IF (iappend) THEN
     IF (PRESENT(file)) THEN
        IF (file == " ") THEN
           CALL message(msg_fatal, &
                "File name must not be empty for appending profiles.")
        ELSE
           filename = TRIM(file)
        ENDIF
     ELSE
        CALL message(msg_fatal, &
             "File name required for appending profiles.")
     ENDIF
  ELSE
     IF (PRESENT(file)) THEN
        IF (file == " ") THEN
           filename = TRIM(filebase) // TRIM(fileext)
        ELSE
           filename = TRIM(file)
        ENDIF
     ELSE
        filename = TRIM(filebase) // TRIM(fileext)
     ENDIF
  ENDIF

! 3.7 Prepend filename with path (if present)
! -------------------------------------------

  IF (PRESENT(path)) THEN
     filename = TRIM(path) // TRIM(filename)
  ENDIF

! 3.8 Write netCDF data file
! --------------------------

  IF (.NOT. ropp_io_ncopensep) THEN

     INQUIRE(file = filename, exist = exist)
     IF (exist .AND. iappend) THEN
        CALL ncdf_open(filename, append = .TRUE.)
     ELSE
        CALL ncdf_create(filename)
        IF (PRESENT(output_precision)) THEN
           CALL ropp_io_write_ncdf_def(ROdata, output_precision)
        ELSE
          CALL ropp_io_write_ncdf_def(ROdata)
        ENDIF
     ENDIF
  ENDIF

  IF (irec <= 0) THEN
     irec = ncdf_getnrec() + 1
  ENDIF
  CALL ropp_io_write_ncdf_put(ROdata, rec = irec)

  IF (.NOT. ropp_io_ncopensep) THEN
     CALL ncdf_close()
  ENDIF

! 3.9 Clean up
! ------------

  IF (.NOT. PRESENT(ierr)) THEN
     CALL message_set_routine(routine)
  ENDIF

END SUBROUTINE ropp_io_write_rodata2d
